# Header
menu:
  主页: /
  所有文章: /archives
  #关于我: /

# SubNav
subnav:
  github: "https://github.com/openboy2012"
  weibo: "http://weibo.com/p/1005051492121455/home"
  #rss: "#"
  zhihu: "http://www.zhihu.com/people/diao-shu-79"
  #douban: "#"
  mail: "Mailto:dongjia_9251@126.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  #rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
#google_analytics: ''
favicon: /favicon.png
baidu_tongji: true

#你的头像url
avatar: "https://avatars1.githubusercontent.com/u/2617618?v=3&s=460"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 钻钻她爹，有强迫症的iOS高级开发工程师...
